Cart
chocom01/harly-outfit pull request #8
Opened 2021-08-05 14:20 UTC by chocom01

2021-08-06 07:09 UTC, Danylo2018 requested changes
Файно попрацював, молодець
Виправиш мої припозиції, чи будеш мати питання, то пиши

2021-08-06 07:09 UTC, Danylo2018 commented on config/routes.rb
> +  resources :orders, only: %i[index create]
мені здається ти не використовуєш `create`

2021-08-06 07:09 UTC, Danylo2018 commented on config/routes.rb
> +  get '/orders/show_cart', to: 'orders#show_cart'
мені здається краще це переписати отак:
```
resources :orders, only: :index do 
    collection do
        get :add_product
        get :show_cart
    end
  end
  ```

2021-08-06 07:17 UTC, Danylo2018 commented on app/views/orders/index.html.erb
> +        <% order.order_items.each do |order_items| %>
Почитай ще про N+1, і подумай чому в тебе буде з цим проблема і як це можна вирішити

2021-08-06 08:21 UTC, chocom01 commented on app/models/order.rb
> +  def sum_products_price
так, в мене з неймінгом трабли(

2021-08-09 07:22 UTC, Danylo2018 commented on app/models/order_item.rb
> +  def item_quantity_increment
ти певен що це та логіка, яку тут треба було реалізувати, я думаю це мало б працювати не як інкрементор. На контролер мала б приходити кількість товару яку хоче замовити користувач, чи я не правий?

2021-08-09 07:23 UTC, Danylo2018 commented on app/models/product.rb
> +  has_many :order_items, dependent: :destroy
треба подумати чи це хороша опція для таких моделей

2021-08-13 09:12 UTC, merged

2021-08-17 08:13 UTC, Danylo2018 commented on app/controllers/orders_controller.rb
> +    cart.order_items.find_or_create_by(product_id: params[:product_id].to_i)
я думаю варто сюди перенести всю логіку з додавання продукту, тобто і кількість змінювати тут жеж, мені виглядає це логічніше, але можеш довести своє рішення
також в цьому методі можна апдейтити суму ордера, і звідси мені виглядає що назва `update_sum_price` краще передає сенс

p.s.  
В мене так часто буває що я змінюю думку щоди назви методів, і мені здається що це окей)

2021-08-17 08:13 UTC, Danylo2018 commented on app/models/order.rb
> +  has_many :order_items, dependent: :destroy
я думаю видалення ордера який принаймні вже оплачений це погана ідея, пошукай рішення, коли матимеш час, як хендлити таку ситуацію

2021-08-17 08:13 UTC, Danylo2018 commented on app/models/order.rb
> +  scope :available_cart, -> { where(status: 'cart') }
ти пхду це ніде не використовуєш, але тут скоуп завжди верне колекцію, а не один об'єкт, тому краще назвати в множині

2021-08-17 08:13 UTC, Danylo2018 commented on app/models/product.rb
> +  has_many :reviews, dependent: :destroy
так само не можна видаляти продукт, і всі решту об'єкти зв'язані вже з оплаченими ордерами

2021-08-17 11:55 UTC, chocom01 commented on app/controllers/orders_controller.rb
> +  def create_empty_cart
поміняв на "find_or_create_cart"

2021-08-17 11:57 UTC, chocom01 commented on app/models/order.rb
> +  scope :available_cart, -> { where(status: 'cart') }
я з ним дещо тестив і забув видалити, щоб вертало 1 треба було find_by, але я його видалив загалом

2021-08-17 12:00 UTC, chocom01 commented on app/models/product.rb
> +  has_many :reviews, dependent: :destroy
поки повидаляв всі "dependent: :destroy"

2021-08-17 12:00 UTC, chocom01 commented on app/models/order.rb
> +  has_many :order_items, dependent: :destroy
поки повидаляв всі "dependent: :destroy"